DROP TABLE IF EXISTS PRODUCT;
 
CREATE TABLE PRODUCT (
  product_id INT AUTO_INCREMENT  PRIMARY KEY,
  product_type VARCHAR(250) NOT NULL,
  colour VARCHAR(50) NOT NULL,
  size VARCHAR(2) DEFAULT NULL,
  price INTEGER,
  brand VARCHAR(100)
);